// Contenido extraído automáticamente de la página web
export const WEB_CONTENT = `CONTENIDO COMPLETO DE LA PÁGINA WEB:

HERO:

About:
- "O3 Energy"
- "Nuestro objetivo es acelerar la transición energética del país a través de la generación de energía limpia, confiable y competitiva, contribuyendo al desarrollo sustentable de México."
- "> Nuestro objetivo es acelerar la transición energética del país a través de la generación de energía limpia, confiable y competitiva, contribuyendo al desarrollo sustentable de México. </p> </div> <div> <img src="
- "Wind turbines"
- "rounded-lg shadow-2xl mx-auto"

AboutSummary:
- "Quiénes Somos"
- "O3 ENERGY MÉXICO"
- "Con una profunda experiencia en el mercado local y un historial de éxito, nos asociamos con propietarios de tierras, comunidades y inversionistas para crear valor duradero y un impacto ambiental positivo."
- "Leer Más"
- "> Con una profunda experiencia en el mercado local y un historial de éxito, nos asociamos con propietarios de tierras, comunidades y inversionistas para crear valor duradero y un impacto ambiental positivo. </p> <a href="
- "> <img src="
- "loading="
- "decoding="

CalculatorPage:
- "Cotizador Solar"
- "Calcule su ahorro con energía solar en solo 4 pasos. Obtenga una cotización personalizada basada en su consumo actual."
- "¿Por qué elegir energía solar?"
- "La energía solar es la inversión más inteligente que existe. Descubra los beneficios y calcule su ahorro potencial."
- "Ahorro Garantizado"
- "Reduzca su factura eléctrica hasta un 95%"
- "Recuperación Rápida"
- "Recupere su inversión en 3-5 años"
- "Energía Limpia"
- "Contribuya al cuidado del medio ambiente"
- "Garantía Extendida"
- "Hasta 25 años de garantía en paneles"
- "Nuestro proceso"
- "Desde la cotización hasta la instalación, estamos con usted en cada paso"
- "Cotización"
- "Complete nuestro formulario y reciba una cotización personalizada en 24 horas"
- "Diseño"
- "Nuestros ingenieros diseñan el sistema perfecto para su propiedad"
- "Instalación"
- "Instalación profesional con garantía de 10 años en la obra"
- "¿Listo para comenzar su proyecto solar?"
- "Nuestro equipo de expertos está listo para ayudarle a encontrar la solución solar perfecta para sus necesidades."
- "Contactar Asesor"
- "Ver Soluciones"
- "> <Link to="
- "> <Link to="
- "> Contactar Asesor </Link> <Link to="

EnergyEfficiencyPage:
- "Eficiencia Energética"
- "Soluciones inteligentes para reducir el consumo de energía y maximizar el rendimiento de sus instalaciones."
- "Solicitar Auditoría"
- "Maximice el Potencial de su Sistema Solar con Eficiencia Energética"
- "Nuestras Soluciones de Eficiencia Energética"
- "Beneficios:"
- "Más información"
- "Beneficios de la Eficiencia Energética"
- "Invertir en eficiencia energética ofrece ventajas que van más allá del ahorro económico."
- "Nuestro Proceso de Eficiencia Energética"
- "Integración con Energía Solar"
- "La combinación de eficiencia energética con energía solar es la fórmula perfecta para maximizar sus ahorros y sostenibilidad. Al reducir su consumo energético total, puede satisfacer una mayor parte de sus necesidades con energía solar, reduciendo aún más su dependencia de la red eléctrica."
- "Un sistema de eficiencia energética bien diseñado puede reducir significativamente el tamaño (y el costo) del sistema solar necesario para cubrir sus necesidades energéticas."
- "¿Listo para Reducir su Consumo Energético?"
- "Nuestros expertos están listos para ayudarle a identificar oportunidades de ahorro y eficiencia en sus instalaciones."
- "Ver Todas las Soluciones"
- "La eficiencia energética no se trata de usar menos energía, sino de usar la energía de manera más inteligente. Al combinar soluciones de eficiencia energética con su sistema solar, puede lograr ahorros aún mayores y reducir significativamente su huella ambiental."
- "Nuestro equipo de expertos en eficiencia energética trabaja junto con nuestros especialistas en energía solar para ofrecerle una solución integral que maximice su inversión y minimice el desperdicio de energía."
- "Conozca nuestras soluciones solares"
- "/>, title:"
- ", description:"
- ", benefits: ["
- "Mayor confort y productividad"
- "Menor huella de carbono"
- "Mejor imagen corporativa"
- "Cumplimiento normativo"
- "Aumento del valor de la propiedad"
- "1. Auditoría Energética"
- "Evaluación detallada del consumo energético de sus instalaciones para identificar oportunidades de mejora."
- "2. Análisis de Viabilidad"
- "Estudio de las soluciones más adecuadas con un análisis detallado de costos y retorno de inversión."
- "3. Implementación"
- "Instalación profesional de las soluciones de eficiencia energética seleccionadas."
- "4. Monitoreo y Seguimiento"
- "Seguimiento continuo del desempeño para garantizar los ahorros esperados."
- "min-h-screen bg-white"
- "relative bg-gradient-to-r from-blue-700 to-blue-900 text-white pt-32 pb-20 -mt-16"
- "container mx-auto px-6"
- "> Soluciones inteligentes para reducir el consumo de energía y maximizar el rendimiento de sus instalaciones. </p> <Link to="
- "currentColor"
- "strokeLinejoin="
- "> <svg xmlns="
- "md:text-left"
- "bg-white p-6 rounded-lg shadow-md border border-gray-100"
- "text-xl font-bold text-green-700 mb-2"
- "text-gray-600"
- "bg-white rounded-xl shadow-lg overflow-hidden border border-gray-100 mb-20"
- "M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
- "> Un sistema de eficiencia energética bien diseñado puede reducir significativamente el tamaño (y el costo) del sistema solar necesario para cubrir sus necesidades energéticas. </p> </div> </div> </div> <Link to="
- "> <Link to="
- "> Solicitar Auditoría </Link> <Link to="

EnergySolutionsPage:
- "Soluciones Energéticas"
- "Soluciones solares llave en mano para el futuro de su negocio"
- "Soluciones Solares Integrales para su Negocio"
- "En O3 ENERGY MEXICO, entendemos que cada negocio es único, con sus propias necesidades y objetivos energéticos. Por eso ofrecemos un amplio rango de soluciones de energía solar diseñadas para ayudar a negocios de todos los tamaños a reducir su huella de carbono, disminuir costos energéticos y alcanzar sus metas de sostenibilidad."
- "Beneficios Adicionales"
- "Para Empresas"
- "Reduzca sus costos operativos y mejore su perfil de sostenibilidad con soluciones solares personalizadas para su negocio."
- "Almacenamiento de Energía"
- "Maximice su independencia energética con sistemas de almacenamiento de batería que le permiten aprovechar al máximo su producción de energía solar."
- "¿Listo para comenzar su viaje hacia la energía limpia?"
- "Nuestro equipo de expertos está listo para ayudarle a encontrar la solución solar perfecta para sus necesidades."
- "Contáctenos"
- "Ver Proyectos"
- "¿Sabía que la energía solar puede hacer más que solo reducir sus costos de electricidad?"
- "/>, title:"
- ", description:"
- ", link:"
- ", linkText:"
- "currentColor"
- "M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z"
- "> <Link to="
- "> Contáctenos </Link> <Link to="

EPCSolarPage:
- "Servicios EPC Solar"
- "Contáctenos para una cotización"
- "Un único punto de contacto para su proyecto solar"
- "Beneficios de Elegir Nuestros Servicios EPC"
- "¿Listo para comenzar su proyecto solar?"
- "Nuestro equipo de expertos está listo para guiarlo a través de cada paso del proceso EPC, asegurando que su proyecto de energía solar sea un éxito."
- "Solicitar Cotización"
- "Volver a Soluciones"
- "Contratarnos como su único proveedor de servicios significa que solo tendrá un número al que llamar para cualquier aspecto de su sistema de energía solar. Hacemos que el acceso a energía limpia y el ahorro de costos sea lo más sencillo posible para usted."
- "/>, title:"
- ", description:"
- "Equipo con amplia experiencia en energía renovable"
- "Soluciones personalizadas para cada cliente"
- "Soporte continuo después de la instalación"
- "Cumplimiento de todas las normativas y permisos"
- "Monitoreo y mantenimiento continuo"
- "min-h-screen bg-white"
- "relative bg-gradient-to-r from-blue-700 to-blue-900 text-white pt-32 pb-20 -mt-16"
- "container mx-auto px-6"
- "currentColor"
- "strokeLinejoin="
- "> <Link to="
- "> Solicitar Cotización </Link> <Link to="

Footer:
- "ENERGY"
- "Navegación"
- "Síguenos"
- "Liderando la transición energética en México."

Hero:
- "Liderando la transición"
- "energética en México"
- "Conócenos"
- "Cotizar Ahora"
- "loading="
- "> <img src="
- "> <a href="
- "aria-label="
- "> Conócenos </a> <a href="

ProjectsPage:
- "Proyectos Solares"
- "Nuestros Proyectos y Casos de Estudio"
- "Desde 2011, hemos proporcionado soluciones de energía renovable y servicios de soporte en toda América del Norte y las Islas del Pacífico. Tómese un momento para ver la prueba del impacto positivo que hemos tenido con nuestros clientes."
- "Ver Nuestras Soluciones"
- "Contáctanos"
- "Ver detalles"
- "No se encontraron proyectos que coincidan con tu búsqueda."
- "Limpiar filtros"
- "¿Listo para comenzar su proyecto solar?"
- "Nuestro equipo de expertos está listo para ayudarle a encontrar la solución solar perfecta para sus necesidades."
- "Solicitar Cotización"
- "Ver Soluciones"
- "> <Link to="
- "> <Link to="
- "/> </Link> <Link to="
- "/> </div> <input type="
- "placeholder="
- "Energía Solar"
- "Energía Eólica"
- "Todas las categorías"
- "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
- "group bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-2"
- "relative h-60 overflow-hidden"
- "w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
- "absolute inset-0 bg-gradient-to-t from-black/70 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6"
- "text-xl font-bold text-white mb-1"
- "text-gray-200"
- "text-[#f36f20] font-semibold mt-2"
- "); setSelectedCategory("
- "> Solicitar Cotización </Link> <Link to="
- "> Ver Soluciones </Link> </div> <a href="

SolarFinancingPage:
- "Financiamiento Solar"
- "Hacemos que la energía solar sea accesible para todos con opciones de financiamiento flexibles y asequibles."
- "Solicitar Cotización"
- "Financiamiento Solar para su Negocio o Hogar"
- "Opciones de Financiamiento Disponibles"
- "Más información"
- "Incentivos Fiscales y Beneficios"
- "Aproveche los incentivos disponibles para hacer que su inversión en energía solar sea aún más atractiva."
- "¿Por qué Financiar su Proyecto Solar?"
- "¿Listo para Descubrir sus Opciones de Financiamiento?"
- "Nuestros expertos en financiamiento están listos para ayudarlo a encontrar la mejor solución para su proyecto solar."
- "Contáctenos"
- "Volver a Soluciones"
- "En O3 ENERGY MEXICO, entendemos que la inversión en energía solar es significativa. Es por eso que ofrecemos diversas opciones de financiamiento para que pueda comenzar a ahorrar desde el primer día, sin necesidad de un desembolso inicial significativo."
- "Ya sea que prefiera ser dueño de su sistema solar o simplemente pagar por la energía que produce, tenemos una solución que se adapta a sus necesidades financieras y objetivos de sostenibilidad."
- "/>, description:"
- ", features: ["
- ", amount:"
- ", description:"
- "> Hacemos que la energía solar sea accesible para todos con opciones de financiamiento flexibles y asequibles. </p> <Link to="
- "> <Link to="
- "currentColor"
- "strokeLinejoin="
- "/>, title:"
- ", description:"
- "> <Link to="
- "> Contáctenos </Link> <Link to="

SolarInstallationPage:
- "Instalación de Paneles Solares"
- "Soluciones de instalación solar sin preocupaciones para su hogar o negocio."
- "Solicitar Cotización"
- "Instalación Solar Sin Preocupaciones"
- "Nuestro Proceso de Instalación"
- "Beneficios de la Energía Solar"
- "Opciones de Financiamiento Flexible"
- "Ofrecemos diversas opciones de financiamiento para que pueda comenzar a ahorrar desde el primer día, sin necesidad de un desembolso inicial significativo."
- "¿Listo para comenzar su proyecto solar?"
- "Nuestro equipo de expertos está listo para guiarlo a través de cada paso del proceso de instalación solar."
- "Contáctenos"
- "Volver a Soluciones"
- "En O3 ENERGY MEXICO, entendemos que la instalación de paneles solares puede parecer abrumadora. Es por eso que hemos simplificado el proceso para que sea lo más sencillo y transparente posible. Desde la evaluación inicial hasta la puesta en marcha, nos encargamos de todo."
- "Con años de experiencia en el sector, hemos completado con éxito instalaciones que van desde pequeños sistemas residenciales hasta grandes proyectos comerciales e industriales, siempre con un compromiso inquebrantable con la calidad y la satisfacción del cliente."
- "/>, title:"
- ", description:"
- "Retorno de inversión atractivo"
- "Solución sostenible y respetuosa con el medio ambiente"
- "Independencia energética de la red eléctrica"
- "Incentivos fiscales disponibles"
- "Aumento del valor de su propiedad"
- "Bajo mantenimiento y larga vida útil"
- "Protección contra el aumento de tarifas eléctricas"
- "min-h-screen bg-white"
- "relative bg-gradient-to-r from-blue-700 to-blue-900 text-white pt-32 pb-20 -mt-16"
- "container mx-auto px-6"
- "> Soluciones de instalación solar sin preocupaciones para su hogar o negocio. </p> <Link to="
- ", description:"
- "md:flex-row-reverse"
- "hidden md:block w-1/2"
- "currentColor"
- "strokeLinejoin="
- ", description:"
- "> <Link to="
- "> Contáctenos </Link> <Link to="

SolarMaintenancePage:
- "Mantenimiento de Sistemas Solares"
- "Mantenga su sistema funcionando al máximo rendimiento con nuestro programa integral de mantenimiento."
- "Solicitar Servicio"
- "Mantenimiento Profesional para su Sistema Solar"
- "Nuestros Servicios de Mantenimiento"
- "Beneficios del Mantenimiento Regular"
- "Invertir en mantenimiento preventivo puede ahorrarle costos significativos a largo plazo."
- "Consejos para el Mantenimiento"
- "Proteja su Inversión"
- "Muchas garantías de fabricantes requieren mantenimiento regular para mantenerse válidas. Nuestro equipo se asegura de que su sistema cumpla con todos los requisitos de garantía y maneja cualquier reclamo de garantía en su nombre."
- "El mantenimiento regular es esencial para mantener válidas las garantías del fabricante. No arriesgue su inversión."
- "Consultar sobre Garantías"
- "¿Listo para Optimizar su Sistema Solar?"
- "Nuestro equipo de expertos está listo para ayudarlo a mantener su sistema funcionando al máximo rendimiento."
- "Solicitar Mantenimiento"
- "Volver a Soluciones"
- "Un sistema solar es una inversión significativa que requiere mantenimiento regular para garantizar su rendimiento óptimo a lo largo del tiempo. En O3 ENERGY MEXICO, ofrecemos servicios completos de mantenimiento diseñados para maximizar la eficiencia y extender la vida útil de su sistema."
- "Nuestro equipo de técnicos certificados está capacitado para realizar inspecciones detalladas, limpieza profesional y diagnósticos avanzados para mantener su sistema funcionando como nuevo."
- "/>, title:"
- ", description:"
- "Extiende la vida útil de su sistema"
- "Mantiene la eficiencia óptima"
- "Previene costosas reparaciones futuras"
- "Garantiza el cumplimiento de garantías"
- "Protección de su inversión a largo plazo"
- "Realice inspecciones visuales periódicas"
- "Mantenga los paneles libres de escombros"
- "Revise regularmente el rendimiento del sistema"
- "Programe mantenimientos profesionales al menos una vez al año"
- "Esté atento a sombras que puedan afectar el rendimiento"
- "Mantenga la vegetación alrededor de los paneles recortada"
- "min-h-screen bg-white"
- "relative bg-gradient-to-r from-blue-900 to-[#022240] text-white pt-32 pb-20 -mt-16"
- "container mx-auto px-6"
- "> Mantenga su sistema funcionando al máximo rendimiento con nuestro programa integral de mantenimiento. </p> <Link to="
- "currentColor"
- "strokeLinejoin="
- "M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
- "> El mantenimiento regular es esencial para mantener válidas las garantías del fabricante. No arriesgue su inversión. </p> </div> </div> </div> <Link to="
- "> <Link to="
- "> Solicitar Mantenimiento </Link> <Link to="

SolarProjectDevelopmentPage:
- "Desarrollo de Proyectos Solares"
- "Soluciones integrales para el desarrollo de proyectos solares a la medida de sus necesidades."
- "Iniciar Proyecto"
- "Expertos en Desarrollo de Proyectos Solares"
- "Nuestro Proceso de Desarrollo"
- "Beneficios de Nuestros Servicios"
- "¿Listo para comenzar su proyecto solar?"
- "Nuestro equipo de expertos está listo para guiarlo a través de cada paso del desarrollo de su proyecto solar."
- "Contáctenos"
- "Volver a Soluciones"
- "En O3 ENERGY MEXICO, nos especializamos en el desarrollo de proyectos solares llave en mano para clientes comerciales e industriales. Nuestro enfoque integral abarca desde la concepción inicial hasta la puesta en marcha y más allá."
- "Con años de experiencia en el sector, hemos completado con éxito proyectos que van desde pequeñas instalaciones hasta plantas solares a gran escala, siempre con un compromiso inquebrantable con la calidad y la satisfacción del cliente."
- "/>, title:"
- ", description:"
- "Retorno de inversión atractivo"
- "Solución sostenible y respetuosa con el medio ambiente"
- "Independencia energética"
- "Incentivos fiscales y financiamiento disponible"
- "Soporte continuo y mantenimiento"
- "min-h-screen bg-white"
- "relative bg-gradient-to-r from-blue-700 to-blue-900 text-white pt-32 pb-20 -mt-16"
- "container mx-auto px-6"
- "> Soluciones integrales para el desarrollo de proyectos solares a la medida de sus necesidades. </p> <Link to="
- "currentColor"
- "strokeLinejoin="
- "> <Link to="
- "> Contáctenos </Link> <Link to="

GENERAL:

BackToTopButton:
- "opacity-0 translate-y-10 pointer-events-none"
- "Volver arriba"
- "currentColor"
- "strokeLinejoin="
- "M5 15l7-7 7 7"

MessageBubble:
- "justify-end"
- "w-8 h-8 bg-[#A4E834] rounded-full flex items-center justify-center flex-shrink-0"
- "text-[#121212]"
- "text-right"
- ", minute:"

Header:
- "ENERGY MEXICO"
- "bg-transparent"
- "container mx-auto px-6 py-4 flex justify-between items-center"
- "text-white hover:text-[#f36f20]"
- "currentColor"
- "strokeLinejoin="
- "/> ) : ( <path strokeLinecap="

OptimizedImage:
- "; quality?: number; sizes?: string; srcSet?: string; placeholder?:"
- "; blurDataURL?: string; placeholderColor?: string; objectFit?:"
- "scale-down"
- ", containerClassName ="
- ", loading: loadingProp ="
- ", quality = 80, sizes ="
- ", srcSet, placeholder ="
- ", blurDataURL, placeholderColor ="
- ", objectFit ="
- "); // if (elem.getContext && elem.getContext("
- ").indexOf("
- ").pop()?.toLowerCase() ||"
- ") || src.startsWith("
- "|| optimizedSrc.startsWith("
- "? placeholderColor :"
- ", backgroundImage: placeholder ==="
- ", backgroundSize:"
- ", backgroundPosition:"
- ": showPlaceholder && placeholder ==="
- ", height: height ||"
- ": !isLoaded,"
- ", height:"
- ", objectFit, objectPosition:"
- "><rect width="

SERVICES:

ChatbotWidget:
- "Asistente O3 ENERGY MEXICO"
- "En línea"
- ", email:"
- ", phone:"
- ", monthlyBill: 0, hasRoofSpace: false, currentStep:"
- ", text:"
- ", sender:"
- ", timestamp: new Date(), type:"
- ", timestamp: new Date(), type:"
- ", timestamp: new Date(), type:"
- ", sender:"
- ") || text.includes("
- ", email:"
- ", phone:"
- ", monthlyBill: 0, hasRoofSpace: false, currentStep:"
- "aria-label="

Services:
- "Nuestros Servicios"
- "Cubrimos todo el ciclo de vida de los proyectos de energía renovable."

ServicesSummary:
- "Lo Que Hacemos"
- "Ofrecemos soluciones integrales para el desarrollo de energía renovable a gran escala."
- "currentColor"
- "strokeLinejoin="
- "strokeWidth="
- "M12 8c-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4-1.79-4-4-4z"
- "M12 2L8 6l4 14 4-14-4-4z"
- "M12 6v6m0 0v6m0-6h6m-6 0H6"
- "M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
- "M12 2c-3.31 0-6 2.69-6 6 0 1.55.58 2.96 1.5 4L4 20h16l-3.5-8A5.94 5.94 0 0018 8c0-3.31-2.69-6-6-6z"
- "Selección y Análisis de Sitios"
- "Identificamos y aseguramos ubicaciones óptimas para proyectos solares, realizando análisis exhaustivos de viabilidad técnica y financiera."
- "Ingeniería y Diseño"
- "Nuestro equipo de ingeniería diseña sistemas solares y de almacenamiento personalizados y de alto rendimiento, optimizados para la máxima producción y longevidad."
- "Gestión de Construcción"
- "opacity-100 translate-y-0"
- "opacity-0 translate-y-10"
- "bg-o3-green/10 text-o3-green rounded-full p-4 mb-6"

Stats:
- ", suffix:"

CONTACT:

ChatWindow:
- "aria-label="

SolarCalculator:
- "¿Dónde instalará sus paneles?"
- "Residencial"
- "Negocio"
- "Comercial"
- "Aislado"
- "Sin red CFE"
- "¿Su recibo CFE le llega?"
- "Mensual"
- "Bimestral"
- "Gasto promedio mensual"
- "¿Desea información?"
- "Financiado"
- "Meses sin intereses"
- "Contado"
- "Pago único"
- "Meses sin Intereses"
- "Financiamiento especial"
- "Información de contacto"
- "Nombre completo"
- "Teléfono"
- "Dirección"
- "Adjuntar recibo CFE (opcional)"
- "Tamaño máximo 15 MB (PDF, JPG, PNG)"
- "¡Tu cotización está lista!"
- "Sistema solar"
- "Paneles solares"
- "Inversión total"
- "Recuperación"
- "Cotizador Solar O3 Energy"
- "¡Haga su propio ejercicio y calcule su ahorro!"
- ", billingFrequency:"
- ", monthlyConsumption:"
- ", paymentMethod:"
- ", name:"
- ", email:"
- ", phone:"
- ", address:"
- "border-[#f36f20] bg-[#f36f20]/10"
- "border-gray-300 hover:border-[#f36f20]/50"
- "font-semibold text-lg"
- "text-sm text-gray-600"
- "paymentMethod"
- ">Nombre completo</label> <input type="
- "placeholder="
- ">Teléfono</label> <input type="
- ">Email</label> <input type="
- ">Dirección</label> <input type="
- ">Adjuntar recibo CFE (opcional)</label> <input type="
- "accept="
- ", e.target.files?.[0] || new File([],"

ABOUT:

Contact:
- "Contacto"
- "Estamos aquí para ayudarte. Contáctanos para más información sobre nuestros servicios de energía solar."
- "Horario de atención"
- "Envíanos un mensaje"
- "Nombre completo *"
- "Correo electrónico *"
- "Teléfono (opcional)"
- "Mensaje *"
- "Lunes - Viernes:"
- "9:00 AM - 6:00 PM"
- "Sábado:"
- "9:00 AM - 2:00 PM"
- "Domingo:"
- "Cerrado"
- "), email: Yup.string().email("
- ").required("
- "), phone: Yup.string().matches(/^[0-9\s+\-()]*$/,"
- "), message: Yup.string().required("
- ").min(10,"
- ", city:"
- ", phone:"
- ", email:"
- "height="
- "title="
- ", message:"
- "bg-red-900/30 text-red-400"
- "> Nombre completo * </label> <Field type="
- "border-gray-700"
- "/> <ErrorMessage name="
- "component="
- "/> </div> <div> <label htmlFor="
- "> Correo electrónico * </label> <Field type="
- "> Teléfono (opcional) </label> <Field type="
- "+52 (__) ____ ____"
- "> Mensaje * </label> <Field as="
- "¿En qué podemos ayudarte?"
- "> <button type="
- "currentColor"
- "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
- "Enviar mensaje"

Locations:
- "Nuestras Ubicaciones"
- "Con presencia en múltiples ubicaciones en América del Norte, estamos listos para atender tus necesidades de energía solar dondequiera que estés."
- "¿Listo para hablar sobre tu proyecto de energía solar?"
- "Nuestro equipo está listo para ayudarte a encontrar la mejor solución de energía renovable para tus necesidades."
- "Contáctanos"
- ", address:"
- ", city:"
- ", phone:"
- ", email:"
- ", mapUrl:"
- ", image:"
- "> Nuestro equipo está listo para ayudarte a encontrar la mejor solución de energía renovable para tus necesidades. </p> <a href="

NewsSummary:
- "Leer Más &rarr;"
- "Últimas Noticias"
- "Manténgase informado sobre las últimas tendencias y noticias del sector energético."
- "Ver Más Noticias"
- ", date:"
- ", excerpt:"
- ", imageUrl:"
- "opacity-0 translate-y-10"
- "overflow-hidden h-56"
- "w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
- "decoding="
- "> <a href="

WhatsAppButton:
- "aria-label="
- "> <svg xmlns="
- "width="
- "height="
- "viewBox="
- "> <path d="
- "/> <path d="

TEAM:

CTA:
- "¿Listo para Empezar tu Próximo Proyecto Solar?"
- "Nuestro equipo está listo para ayudarle a alcanzar sus objetivos de energía renovable. Contáctenos hoy para una consulta gratuita."
- "Solicitar Cotización"
- "> <a href="

Team:
- "Nuestro Equipo"
- "+ member.name.replace(/\s+/g,"
- "&background=random"
- "text-xl font-bold text-white mb-1"
- "text-[#f36f20] font-medium"

PROJECTS:

FeaturedProjects:
- "Proyectos Destacados"
- "Ver Todos los Proyectos &rarr;"
- ", location:"
- ", imageUrl:"
- "opacity-0 translate-y-10"
- "w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
- "decoding="
- ">Proyectos Destacados</h2> <a href="
- "> <a href="

Projects:
- "Nuestros Proyectos"
- "Ver todos los proyectos"
- "> <Link to="
- "currentColor"
- "M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z"

`;

export const getWebContent = () => WEB_CONTENT;
